# Site settings
title: secur.codes - Secure Your Codes
description: >- # this means to ignore newlines until "baseurl:"
  Professional cybersecurity services including secure code review, application penetration testing, network vulnerability assessment and host security assessment.

# Contact information
street_address: 1234 Somewhere Road
city: Nashville
state: TN
zip_code: 55555
country: United States of America
phone: (302) 612-5709
email: make@secur.codes

# Social settings
500px:
  url:
  label: 
facebook:
  url: https://github.com/moodule
  label:
github:
  url: https://github.com/moodule
  label:
gitlab:
  url:
  label:
instagram:
  url: https://github.com/moodule
  label:
linkedin:
  url:
  label:
medium:
  url: https://github.com/moodule
  label:
pinterest:
  url:
  label:
slack:
  url:
  label:
snapchat:
  url: https://github.com/moodule
  label:
twitter:
  url: https://github.com/moodule
  label:

# Optional elements
logo: /assets/images/logo.png
favicon: /assets/images/favicon.ico
legal_terms:
  url: /en/legal-terms/
privacy_policy:
  url: /en/privacy-policy/
  third_party:
    hosting: github

# Recaptcha in forms
recaptcha:
  sitekey: 6LfMccgUAAAAAJcASCBTwXpeEXw7qjC-KkqjpsYV
  secretkey: 6LfMccgUAAAAAEYb9GfycbY2FQR_EcEypQFG1_32

# Collections
collections:
  redirects:
    output: true
    permalink: /:path/

# Default settings
defaults:
  -
    scope:
      type: "redirects"
    values:
      layout: "redirect"
      lang: "x-default"
  -
    scope:
      path: ""
    values:
      menu: default
  -
    scope:
      path: "en"
    values:
      lang: "en"
  -
    scope:
      path: "fr"
    values:
      lang: "fr"

# Build settings
permalink: pretty
markdown: kramdown
sass:
  sourcemap: never
  style: compressed
    #plugins:
    #- jekyll-seo-tag

# Publication settings
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://localhost:4000" # the base hostname & protocol for your site, e.g. http://example.com
author: Derek Callaway
copyright:
  holder: secur.codes
  license: 

# Exclude from processing
